In [1]:
# !pip install numpy

# Numpy

In [2]:
import numpy as np

In [3]:
lista_np = np.array([1, 2, 3, 4, 5])

In [4]:
lista_np

array([1, 2, 3, 4, 5])

In [5]:
lista = [1, 2, 3, 4, 5]

In [6]:
lista

[1, 2, 3, 4, 5]

In [7]:
type(lista_np)

numpy.ndarray

In [8]:
type(lista)

list

In [10]:
lista_np.dtype

dtype('int32')

In [25]:
lista_float = np.array([1.0, 2.0, 4.0, 5.0])

In [26]:
lista_float.dtype

dtype('float64')

In [27]:
print(lista_float)

[1. 2. 4. 5.]


In [31]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [34]:
[i for i in range(5, 50, 5)]

[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [39]:
vector = np.arange(12)

In [40]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
vector.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
tensor = vector.reshape(3, 2, 2)

In [43]:
[[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]]

[[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]]

In [44]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
vector[4]

4

In [47]:
tensor

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [50]:
tensor[1][0][1]

5

In [54]:
vector[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# np.linspace()

In [64]:
np.linspace(start=10, stop=20, num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

# np.zeros() & np.ones()

In [68]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [70]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Arreglos aleatorios

In [79]:
np.random.rand(10)

array([0.05459255, 0.42071165, 0.74449558, 0.79017338, 0.37970756,
       0.34916091, 0.76882762, 0.40308394, 0.40757964, 0.45552152])

In [76]:
# Lista de 10 elementos al azar entre 10 y 15 con distribución uniforme
np.random.uniform(low=10, high=15, size=10)

array([11.22547214, 10.43608568, 14.70257098, 11.09886715, 11.70304876,
       13.86971402, 10.46813113, 10.76403316, 10.65859837, 13.45405947])

In [90]:
# Array con 10 elementos con distribución normal con media = 0, desviación estandar = 1
np.random.normal(loc=0, scale=1, size=10)

array([ 0.75739648,  1.42410196, -0.81301699, -2.25544845,  1.29786762,
       -1.18596046, -1.09954228, -0.48938025, -2.86539041, -0.36327488])

In [88]:
# Array de números enteros al azar
np.random.randint(10, 20, 10)

array([15, 11, 13, 15, 19, 14, 10, 16, 15, 16])

# flatten()

In [93]:
tensor

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [92]:
tensor.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
tensor.shape

(3, 2, 2)

In [120]:
np.array([1, 2, 3]).shape

(3,)

In [122]:
np.array([[1, 2, 3]]).shape

(1, 3)

In [123]:
np.array([[1], [2], [3]]).shape

(3, 1)

# Operaciones

In [96]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [97]:
lista_1 + lista_2

[1, 2, 3, 4, 5, 6]

In [103]:
arr_1 = np.arange(1, 4)
print(arr_1)

[1 2 3]


In [100]:
arr_2 = np.arange(4, 7)

In [104]:
print(arr_2)

[4 5 6]


In [105]:
arr_1 + arr_2

array([5, 7, 9])

In [114]:
matriz_1 = np.array([[2, 3], [2, 3], [2, 3], [3, 4], [3, 4]])

In [115]:
print(matriz_1)

[[2 3]
 [2 3]
 [2 3]
 [3 4]
 [3 4]]


In [116]:
matriz_2 = np.array([[1, 2, 3, 5, 7], [4, 2, 3, 0, 1]])

In [117]:
print(matriz_2)

[[1 2 3 5 7]
 [4 2 3 0 1]]


In [118]:
np.matmul(matriz_1, matriz_2)

array([[14, 10, 15, 10, 17],
       [14, 10, 15, 10, 17],
       [14, 10, 15, 10, 17],
       [19, 14, 21, 15, 25],
       [19, 14, 21, 15, 25]])

In [119]:
np.matmul(matriz_2, matriz_1)

array([[48, 66],
       [21, 31]])

# Referencias


### Repositorio

https://drive.google.com/drive/u/0/folders/1KRiYCDqOQZl17HdU1EEJkSLx5WitItH0


### Ejercicios Numpy

https://github.com/rougier/numpy-100/tree/master


### Introducción a Numpy y Matplotlib

https://sebastianraschka.com/blog/2020/numpy-intro.html


### Documentación oficial de Numpy

https://numpy.org/