# Práctica Clase 3

## Numpy

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]

In [3]:
print(lista)

[1, 2, 3, 4, 5, 6]


In [4]:
type(lista)

list

In [5]:
array = np.array([1, 2, 3, 4, 5, 6])

In [6]:
print(array)

[1 2 3 4 5 6]


In [7]:
type(array)

numpy.ndarray

# slicing

In [9]:
lista[:3]

[1, 2, 3]

In [20]:
array[:3]

array([1, 2, 3])

In [21]:
lista[::-1]

[6, 5, 4, 3, 2, 1]

In [22]:
array[::-1]

array([6, 5, 4, 3, 2, 1])

# sumar elementos

In [23]:
print(lista)

[1, 2, 3, 4, 5, 6]


In [24]:
sum(lista)

21

In [25]:
print(array)

[1 2 3 4 5 6]


In [26]:
np.sum(array)

21

In [31]:
lista.append(7)

In [32]:
lista

[1, 2, 3, 4, 5, 6, 7]

In [34]:
np.append(array, 7)

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
lista.insert(0, 100)

In [36]:
lista

[100, 1, 2, 3, 4, 5, 6, 7]

In [44]:
array = np.insert(array, 0, 100)

In [45]:
array

array([100,   1,   2,   3,   4,   5,   6])

In [41]:
np.insert(array, 2, [69, 67])

array([ 1,  2, 69, 67,  3,  4,  5,  6])

In [42]:
max(lista)

100

In [46]:
np.max(array)

100

In [47]:
min(lista)

1

In [48]:
np.min(array)

1

¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.

In [52]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [53]:
[i + 1 for i in lista]

[101, 2, 3, 4, 5, 6, 7, 8]

In [51]:
array + 1

array([101,   2,   3,   4,   5,   6,   7])

In [54]:
lista * 3

[100, 1, 2, 3, 4, 5, 6, 7, 100, 1, 2, 3, 4, 5, 6, 7, 100, 1, 2, 3, 4, 5, 6, 7]

In [55]:
array * 3

array([300,   3,   6,   9,  12,  15,  18])

In [56]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [57]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [58]:
np.array([1, 2, 3]) + [4, 5, 6]

array([5, 7, 9])

¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [65]:
print('Arreglo de (n,)')
arreglo = np.array([1, 2, 3, 4, 5, 6])
print(arreglo, '\nShape = ', arreglo.shape, '\n')

Arreglo de (n,)
[1 2 3 4 5 6] 
Shape =  (6,) 



In [64]:
print('Arreglo de (2, n)')
arreglo_2 = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
print(arreglo_2, '\nShape = ', arreglo_2.shape, '\n')

Arreglo de (2, n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] 
Shape =  (2, 6) 



In [66]:
print('Arreglo de (n, 2)')
arreglo_2 = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
print(arreglo_2.T, '\nShape = ', arreglo_2.T.shape, '\n')

Arreglo de (n, 2)
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]] 
Shape =  (6, 2) 



In [71]:
arreglo_2.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [81]:
print('Arreglo de (2, n)')
arreglo_2 = np.array([[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]])
print(arreglo_2, '\nShape = ', arreglo_2.shape, '\n')

Arreglo de (2, n)
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]] 
Shape =  (6, 2) 



**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.linspace(0, 9, 100)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [85]:
arreglo = np.arange(10, 101)

In [86]:
print(arreglo)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [88]:
mascara = (arreglo % 3 == 0)

In [89]:
arreglo[mascara]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [96]:
arreglo[(arreglo % 3 == 0) & (arreglo > 50)]

array([51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [93]:
def multiplos_de_tres(arr):
    lista_final = []
    for i in arr:
        if i % 3 == 0:
            lista_final.append(i)
    return np.array(lista_final)

In [94]:
multiplos_de_tres(arreglo)

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [98]:
ceros = np.zeros((5, 10))

In [99]:
ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
ceros[[1, 3]] = 1

In [111]:
ceros

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

In [112]:
ceros[:, [2, 7]] = 2

In [118]:
ceros[:, [1, 4, 5]] = 100

In [120]:
ceros

array([[  0., 100.,   2.,   0., 100., 100.,   0.,   2.,   0.,   0.],
       [  1., 100.,   2.,   1., 100., 100.,   1.,   2.,   1.,   1.],
       [  0., 100.,   2.,   0., 100., 100.,   0.,   2.,   0.,   0.],
       [  1., 100.,   2.,   1., 100., 100.,   1.,   2.,   1.,   1.],
       [  0., 100.,   2.,   0., 100., 100.,   0.,   2.,   0.,   0.]])

In [126]:
ceros.shape[1]

10

In [127]:
ceros[[1, 2, 3]] = 0

In [130]:
ceros[:] = 0

In [131]:
ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
ceros[:, [0, 2, 4, 6, 8]] = 0

In [138]:
ceros

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html