# Práctica Clase 3

## Numpy

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [2]:
import numpy as np

In [4]:
# Operaciones que se pueden hacer en las dos.

lista1 = [1,2,3]
lista2 = [4,5,6]
arrey1 = np.array([1,2,3])
arrey2 = np.array([4,5,6])

#Podemos obtener el tamaño de una lista y de un arreglo.
print(len(lista1))
print(len(lista2))
print(arrey1.size)
print(arrey2.size)


3
3
3
3


In [5]:
# Al sumar dos listas de python, estas se concatenan (no se hace una suma matemática de las listas), mientras que con dos arreglos la suma se realiza.

print(lista1 + lista2)
print(arrey1 + arrey2)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [11]:
# Creamos 3 arreglos, cada uno con la condición especificada: (n,), (n,1) y (1,n), donde n = 6.

an = np.arange(6)
print(an)
print(an.shape)

an1 = an.reshape(6,1)
print(an1)
print(an1.shape)

a1n = an.reshape(1,6)
print(a1n)
print(a1n.shape)

# Como se observa dentro de los prints, en el caso de (n,) tenemos un arreglo de 1 dimensión con 6 elementos. En (n,1) tenemos un arreglo donde la primera lista tiene 6 listas, cada una de 1 elemento. En (1,n) tenemos un arreglo donde la primera lista contiene una lista de 6 elementos.

[0 1 2 3 4 5]
(6,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)
[[0 1 2 3 4 5]]
(1, 6)


**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [13]:
a1 = np.arange(0,9)

In [14]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a2 = np.linspace(0,9,100)

In [16]:
a2

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [17]:
import numpy as np
import numpy.ma as ma

In [18]:
x = np.arange(10,100)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [26]:
z = ma.masked_where(x%3 != 0,x)
z

masked_array(data=[--, --, 12, --, --, 15, --, --, 18, --, --, 21, --, --,
                   24, --, --, 27, --, --, 30, --, --, 33, --, --, 36, --,
                   --, 39, --, --, 42, --, --, 45, --, --, 48, --, --, 51,
                   --, --, 54, --, --, 57, --, --, 60, --, --, 63, --, --,
                   66, --, --, 69, --, --, 72, --, --, 75, --, --, 78, --,
                   --, 81, --, --, 84, --, --, 87, --, --, 90, --, --, 93,
                   --, --, 96, --, --, 99],
             mask=[ True,  True, False,  True,  True, False,  True,  True,
                   False,  True,  True, False,  True,  True, False,  True,
                    True, False,  True,  True, False,  True,  True, False,
                    True,  True, False,  True,  True, False,  True,  True,
                   False,  True,  True, False,  True,  True, False,  True,
                    True, False,  True,  True, False,  True,  True, False,
                    True,  True, False,  True,  True, Fa

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [48]:
c = np.zeros(50,int)

s = c.reshape(5,10)
s

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
# Reemplazamos la fila 2 y 4 con "1".

s[1] = s[1] = 1
s[3] = s[3] = 1

s


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
# Reemplazamos la columna 3 y 8 con "2"

s[:,2] = 2
s[:,7] = 2

s

array([[0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0]])

In [43]:
# Ejemplo de internet con el cambio de columnas.

import numpy as np

new_arr = np.ones((3,3))
print("Creation of array:",new_arr)
new_arr[:, 1] =  0
print("Replace column from array:",new_arr)

Creation of array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Replace column from array: [[1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]


In [46]:
# Ejemplo de internet con el cambio de filas.
import numpy as np

new_array = np.array([[15, 17, 35],
                   [18, 22, 34],
                   [78, 84, 34]])

print(new_array)

new_array[2:,] = new_array[2:,] * 4
print(new_array)

[[15 17 35]
 [18 22 34]
 [78 84 34]]
[[ 15  17  35]
 [ 18  22  34]
 [312 336 136]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html