In [2]:
import numpy as np

In [3]:
lista_np = np.array([1,2,3,4,5])

In [4]:
lista = [1,2,3,4,5]

In [5]:
type(lista_np)

numpy.ndarray

In [6]:
type(lista)

list

In [7]:
lista_np.dtype

dtype('int32')

In [8]:
lista_float = np.array([1.0,2,3,5,0]) #Todos los datosen los array tienen que ser del mismo tipo. Por ejemplo, Si en una lista de int tiene un string, lo va a convertir todo en str. Ya que busca agrupar el tipo más abarcativo.

lista_float.dtype

dtype('float64')

In [9]:
np.arange(5,50) # "np.arange(dato,dato final,condición)" Crea un array entre un dato y otro

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
np.arange(5,50,5) #Crea un array entre un dato y otro cumpliendo una condición.

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
np.arange(12).reshape(3,4) # ".reshape(filas,columnas)" Crea una matriz, donde el primer dato es el número de filas (o listas) y el segundo el número de columnas (o número de valores por lista).

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
vector = np.arange(12)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
tensor = vector.reshape(3,2,2) #Crea tensores a partir de los datos. Se entiende como una lista con 3 dimensiones.Así, se tiene: dim 1) una lista, dim 2) tres listas, dim 3) dos listas de dos datos c/u.

# Se puede entender como "lista anidada" también.
tensor

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [14]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
vector[4] #se pueden obtener datos en los índices.

4

In [16]:
tensor[1][0][1] #Se obtiene, del segundo elemento, el primer elemento, el segundo dato.

5

In [17]:
vector[-1] #Último elemento.

11

In [18]:
vector[5:] #Del elemento 6 al último elemento.

array([ 5,  6,  7,  8,  9, 10, 11])

np.linspace()

In [19]:
np.linspace(start=10,stop=20,num=5) #Crea una lista con el número de elementos (num) equidistantes entre el elemento start y el elemento stop (incluye al elemento stop).

array([10. , 12.5, 15. , 17.5, 20. ])

np.zeros() & np.ones()

In [20]:
np.zeros(5,dtype=int) #Crea una lsita con el número de zeros indicados, con el tipo indicado.

array([0, 0, 0, 0, 0])

In [21]:
np.ones(10) #Crea una lista con el número de 1 indicados.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Arrays aleatorios

In [22]:
np.random.rand(10) #crea números aleatorios

array([0.99477427, 0.49947283, 0.31464028, 0.73025643, 0.66306128,
       0.89770395, 0.25213932, 0.68901655, 0.25538521, 0.90793279])

In [24]:
np.random.uniform(low=10, high=15,size=10) #crea un array con una distribución uniforme (o donde todos los valores tienen la misma probabilidad de salir)

array([10.87201468, 14.66020573, 10.90315682, 12.37386708, 13.00585736,
       10.24289789, 10.44088468, 14.4021191 , 10.94287358, 14.21313406])

In [25]:
np.random.normal(loc=0,scale = 1,size=10) #Crea un array con diez elementos con distribución normal con media 0, desviación estándar de 1.

array([-0.60902622,  0.45680299,  1.30784153,  0.48370459,  1.22684587,
        0.43392842,  0.45652386,  0.70332792, -1.0652971 ,  1.29264517])

In [26]:
#Array de números enteros al azar
np.random.randint(10,20,10) #Lista de 10 elementos entre 10 y 20.

array([13, 17, 13, 12, 11, 16, 18, 11, 12, 19])

flatten()

In [27]:
tensor.flatten() #le quita las dimensiones al array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Shape

In [29]:
tensor.shape #Te dice el número de dimensiones, y el valor en cada una. 

(3, 2, 2)

Operaciones

In [31]:
lista_1 = [1,2,3]
lista_2 = [4,5,6]

In [32]:
#En python
lista_1 + lista_2 #Concatena las listas

[1, 2, 3, 4, 5, 6]

In [33]:
#En np
arr1 = np.arange(1,4)
print(arr1)
arr2 = np.arange(4,7)
print(arr2)

[1 2 3]
[4 5 6]


In [34]:
arr1 + arr2 #Suma las listas.

array([5, 7, 9])

In [36]:
matriz1 = np.array([[2,3], [2,3], [2,3]])
matriz1

array([[2, 3],
       [2, 3],
       [2, 3]])

In [39]:
matriz2 = np.array([[1,2,3,5,7],[4,2,3,0,1]])
matriz2

array([[1, 2, 3, 5, 7],
       [4, 2, 3, 0, 1]])

In [40]:
np.matmul(matriz1,matriz2) #Multiplicación de matrices.

array([[14, 10, 15, 10, 17],
       [14, 10, 15, 10, 17],
       [14, 10, 15, 10, 17]])